settings:
  world: "world"
  attempts: 50
  safe-radius: 16
  cooldown-seconds: 60
  max-range: 10000

sounds:
  success:
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.0

  animation-tick:
    sound: "BLOCK_LEVER_CLICK"
    volume: 0.8
    pitch: 1.2

  error:
    sound: "BLOCK_NOTE_BLOCK_BASS"
    volume: 1.0
    pitch: 0.8

gui:
  size: 45
  title: "&535b68               &333840» &535b68RTP &333840«"

  background-item:
    material: GRAY_STAINED_GLASS_PANE
    name: " "

  buttons:
    normal:
      slot: 20
      material: ENDER_PEARL
      name: "&7"
      lore:
        - " &b3dfd0♪ Обычный телепорт"
        - "&7"
        - " &77ffef⚑ Дальность: &a8fff5&l1000 блоков &a8fff5от спавна "
        - " &77c3ff♯ Опасность: &a8dbff&lНизкая "
        - " &778cff☑ Доступность: &a8abff&lВсем "
        - "&7"
        - " &a1ead1• Телепортирует вас в рандомную точку мира "
        - "&7"
      highlight:
        material: LIGHT_BLUE_STAINED_GLASS_PANE
        slots: [10,11,12,19,20,21,28,29,30]

    nearest:
      slot: 24
      material: RECOVERY_COMPASS
      name: "&7"
      lore:
        - " &dfb3b3♫ Ближайший телепорт"
        - "&7"
        - " &ff8a77⚑ Дальность: &ffb3a8&l250 блоков &ffb3a8до ближайшего игрока "
        - " &ffa677♯ Опасность: &ffc8a8&lСредняя "
        - " &ffe277☑ Доступность: &ffefa8&lВсем "
        - "&7"
        - " &eab3a1• Телепортирует вас к ближайшему игроку "
        - ""
      highlight:
        material: RED_STAINED_GLASS_PANE
        slots: [14,15,16,23,24,25,32,33,34]

messages:
  no_players_online:
    - '&7'
    - "&c72b2b ❌  &ff9089|  &ff5a5aНет достаточного кол-ва игроков"
    - '&7'
  teleporting:
    - '&7'
    - "&e7a924 ⏳  &ffe189|  &e7a924Телепортация..."
    - '&7'
  teleported:
    - '&7'
    - "&24e765 ✔  &89ffa6|  &24e765Вы успешно перемещены!"
    - '&7'
  cooldown:
    - '&7'
    - "&c72b2b ❌  &ff9089|  &ff5a5aПодождите &ff6262&l%time% &ff5a5aсек."
    - '&7'
  cancelled:
    - '&7'
    - "&c72b2b ❌  &ff9089|  &ff5a5aВы двигаетесь. Телепортация отменена!"
    - '&7'

title-animation:
  interval-ticks: 10
  titles:
    - "&ffb362&m &m"
    - "&ffb362&m  &m"
    - "&ffb362&m   &m"
    - "&ffb362&m    &m"
    - "&ffb362&m   &m"
    - "&ffb362&m  &m"
    - "&ffb362&m &m"
  subtitles:
    - "&7Ожидайте..."
    - "&7Ожидайте.."
    - "&7Ожидайте."
    - "&7Ожидайте.."
    - "&7Ожидайте..."
    - "&7Ожидайте.."
    - "&7Ожидайте."

titles:
  cancel:
    title: "&ff5743&lТелепорт отменен"
    subtitle: "&7Вы пошевелились"

  success:
    title: "&a5ff51&lТелепортация успешна"
    subtitle: "&7Приятной игры!"

#
#         *        .        ✦          .             .         *
#        .                *        .         ✷             ✧        .
#               .        ⋆    *         ✧         *      ⋆          .
#  ⋆           .        .        ⋆     .             ⋆       .     .
#        ✷         .       *         ✦     ⋆      .     ⋆      *
# .      ⋆    ⋆        .         ✧       ⋆     ✦           ⋆         ✦
#        .    ⋆         ✷             ⋆          ⋆    ✧      .      ⋆
# ✷      .        ⋆     .    ⋆      ☄       ⋆     .     ⋆     ✧        .
#       .    ✦       .      ⋆       ⋆      ✷        .        ⋆       .
#             ⋆        ⋆        ✷           .         ✦      ⋆
#  ⋆    .       ✦       ⋆       .     𝒷𝓎       ✷        ✦        ⋆       ✷
#       .         ✷        ⋆        𝓈𝓁𝓎𝓅𝒽  .         ✧    ⋆         ⋆
#   ✷          .        .      ⋆  𝒾𝓃 ２０２５  .             ⋆        .      .
#        .          ⋆    *         ✦         *      ⋆          .
#            .                *        .         ✷             ✧        .
#        ✷         .       *         ✦     ⋆      .     ⋆      *
# .      ⋆    ⋆        .         ✧       ⋆     ✦           ⋆         ✦
#        .    ⋆         ✷             ⋆          ⋆    ✧      .      ⋆
# ✷      .        ⋆     .    ⋆      ☄       ⋆     .     ⋆     ✧        .
#       .    ✦       .      ⋆       ⋆      ✷        .        ⋆      .
#             ⋆        ⋆        ✷           .         ✦      ⋆
#         *        .        ✦          .             .         *
#
