# RandomTeleport – конфигурация GUI и логики
settings:
  world: "world"
  attempts: 50
  safe-radius: 16
  cooldown-seconds: 3600
  max-range: 10000

sounds:
  success:                       # уже было
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.0

  animation-tick:                # НОВОЕ — играет на каждый кадр анимации
    sound: "BLOCK_LEVER_CLICK"   # любой enum из org.bukkit.Sound
    volume: 0.8
    pitch: 1.2

  error:                         # НОВОЕ — при сообщении об ошибке
    sound: "BLOCK_NOTE_BLOCK_BASS"
    volume: 1.0
    pitch: 0.8

gui:
  size: 45
  title: "&a&lМеню &fRTP"

  background-item:
    material: GRAY_STAINED_GLASS_PANE
    name: " "

  buttons:
    normal:
      slot: 20
      material: ENDER_PEARL
      name: "&bОбычный телепорт"
      lore:
        - "&7Телепортирует вас"
        - "&7в случайную позицию"
      highlight:
        material: LIGHT_BLUE_STAINED_GLASS_PANE
        slots: [10,11,12,19,20,21,28,29,30]

    nearest:
      slot: 24
      material: COMPASS
      name: "&dБлижайший телепорт"
      lore:
        - "&7Телепортирует на"
        - "&7минимум 250 блоков"
      highlight:
        material: RED_STAINED_GLASS_PANE
        slots: [14,15,16,23,24,25,32,33,34]

messages:
  no_players_online:
    - "&FF5555&lНет достаточного количества игроков!"
  teleporting:
    - "&55FF55Телепортация..."
  teleported:
    - "&55FF55Вы перемещены!"
  cooldown:
    - "&FF5555Подождите &e%time% &cсек."

title-animation:
  interval-ticks: 15
  titles:
    - "&aТелепортация"
    - "&bТелепортация"
    - "&cТелепортация"
  subtitles:
    - "&7Ожидайте..."
    - "&7Ожидайте.."
    - "&7Ожидайте."

#
#         *        .        ✦          .             .         *
#        .                *        .         ✷             ✧        .
#               .        ⋆    *         ✧         *      ⋆          .
#  ⋆           .        .        ⋆     .             ⋆       .     .
#        ✷         .       *         ✦     ⋆      .     ⋆      *
# .      ⋆    ⋆        .         ✧       ⋆     ✦           ⋆         ✦
#        .    ⋆         ✷             ⋆          ⋆    ✧      .      ⋆
# ✷      .        ⋆     .    ⋆      ☄       ⋆     .     ⋆     ✧        .
#       .    ✦       .      ⋆       ⋆      ✷        .        ⋆       .
#             ⋆        ⋆        ✷           .         ✦      ⋆
#  ⋆    .       ✦       ⋆       .     𝒷𝓎       ✷        ✦        ⋆       ✷
#       .         ✷        ⋆        𝓈𝓁𝓎𝓅𝒽  .         ✧    ⋆         ⋆
#   ✷          .        .      ⋆  𝒾𝓃 ２０２５  .             ⋆        .      .
#        .          ⋆    *         ✦         *      ⋆          .
#            .                *        .         ✷             ✧        .
#        ✷         .       *         ✦     ⋆      .     ⋆      *
# .      ⋆    ⋆        .         ✧       ⋆     ✦           ⋆         ✦
#        .    ⋆         ✷             ⋆          ⋆    ✧      .      ⋆
# ✷      .        ⋆     .    ⋆      ☄       ⋆     .     ⋆     ✧        .
#       .    ✦       .      ⋆       ⋆      ✷        .        ⋆      .
#             ⋆        ⋆        ✷           .         ✦      ⋆
#         *        .        ✦          .             .         *
#