name: RandomTeleport
main: com.slyph.randomteleport.RandomTeleportPlugin
version: 1.2.1
api-version: 1.16
authors: [slyph]

libraries:
  - "net.kyori:adventure-api:4.17.0"
  - "net.kyori:adventure-platform-bukkit:4.3.0"

commands:
  rtp:
    description: Открывает меню рандомной телепортации или перезагружает плагин
    usage: /rtp [reload]
    aliases: []
    permission: randomteleport.use

permissions:
  randomteleport.use:
    description: Разрешает использование /rtp
    default: true
  randomteleport.reload:
    description: Перезагрузка плагина (/rtp reload)
    default: op
